version: "3.5"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
    env_file:
      - ./zookeeper.env

  kafka:
    image: confluentinc/cp-kafkacat
    ports:
      - 9092:9092
    env_file:
      - ./kafka.env
    depends_on:
      - zookeeper

